
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ihe.iti.xds_b._2007;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-11T11:17:20.707-04:00
 * Generated source version: 3.0.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "DocumentRepository_Service",
                      portName = "DocumentRepository_Port_Soap12",
                      targetNamespace = "urn:ihe:iti:xds-b:2007",
                      wsdlLocation = "classpath:xds/XDSb.wsdl",
                      endpointInterface = "ihe.iti.xds_b._2007.DocumentRepositoryPortType")
                      
public class DocumentRepository_Port_Soap12Impl implements DocumentRepositoryPortType {

    private static final Logger LOG = Logger.getLogger(DocumentRepository_Port_Soap12Impl.class.getName());

    /* (non-Javadoc)
     * @see ihe.iti.xds_b._2007.DocumentRepositoryPortType#documentRepositoryRetrieveDocumentSet(ihe.iti.xds_b._2007.RetrieveDocumentSetRequestType  body )*
     */
    public ihe.iti.xds_b._2007.RetrieveDocumentSetResponseType documentRepositoryRetrieveDocumentSet(RetrieveDocumentSetRequestType body) { 
        LOG.info("Executing operation documentRepositoryRetrieveDocumentSet");
        System.out.println(body);
        try {
            ihe.iti.xds_b._2007.RetrieveDocumentSetResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ihe.iti.xds_b._2007.DocumentRepositoryPortType#documentRepositoryProvideAndRegisterDocumentSetB(ihe.iti.xds_b._2007.ProvideAndRegisterDocumentSetRequestType  body )*
     */
    public oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponseType documentRepositoryProvideAndRegisterDocumentSetB(ProvideAndRegisterDocumentSetRequestType body) { 
        LOG.info("Executing operation documentRepositoryProvideAndRegisterDocumentSetB");
        System.out.println(body);
        try {
            oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
